"""empty message

Revision ID: 851730ce875a
Revises: 
Create Date: 2024-05-09 00:15:19.393241

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '851730ce875a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('cpf', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('cpf')
    )
    op.create_table('orders',
    sa.Column('order_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('CANCELED', 'TO_BE_PAYED', 'RECIEVED', 'PREPARING', 'READY', 'COMPLETED', name='orderstatusenum'), nullable=False),
    sa.Column('waiting_time', sa.Integer(), nullable=True),
    sa.Column('client_id', sa.String(), nullable=True),
    sa.Column('payment_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.cpf'], ),
    sa.PrimaryKeyConstraint('order_id')
    )
    op.create_table('ordered_products',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('observation', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.order_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ordered_products')
    op.drop_table('orders')
    op.drop_table('clients')
    # ### end Alembic commands ###
