apiVersion: v1
kind: Service
metadata:
  name: orders-svc
  namespace: "default"
  labels:
    app: orders-app
spec:
  type: LoadBalancer
  ports:
  - port: 5000
    targetPort: 5000
  selector:
    app: orders-app
