apiVersion: v1
kind: Service
metadata:
  name: orders-svc
  labels:
    app: orders-app
    service: orders-app
spec:
  ports:
  - port: 5000
    name: http
  selector:
    app: orders-app
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: delivery-orders
  labels:
    account: orders
