
apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-postgres
spec:
  selector:
    matchLabels:
      app: orders-postgres
  replicas: 1
  template:
    metadata:
      labels:
        app: orders-postgres
    spec:
      containers:
      - name: orders-postgres
        image: postgres:13
        imagePullPolicy: "IfNotPresent"
        resources:
          limits:
            memory: "512Mi"
            cpu: "512m"
        ports:
        - containerPort: 5432
        env:
          - name: POSTGRES_DB
            valueFrom:
              secretKeyRef:
                name: orders-database-secret-config
                key: dbname
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: orders-database-secret-config
                key: username
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: orders-database-secret-config
                key: password
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: orders-postgresdb
      volumes:
      - name: orders-postgresdb
        persistentVolumeClaim:
          claimName: orders-postgres-pvc
---
kind: Service
apiVersion: v1
metadata:
  name: orders-postgres-svc
spec:
  selector:
    app: orders-postgres
  ports:
  - port: 5432
  type: ClusterIP